# Generated by Django 5.1.4 on 2025-05-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
