# Generated by Django 5.1.4 on 2025-05-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_product_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="pet_category",
            field=models.CharField(
                choices=[
                    ("DOG", "Dog"),
                    ("CAT", "Cat"),
                    ("BIRD", "Bird"),
                    ("FISH", "Fish"),
                    ("REPTILE", "Reptile"),
                    ("SMALL_ANIMAL", "Small Animal"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("TOY", "Toy"),
                    ("ACCESSORY", "Accessory"),
                    ("HEALTH", "Health Care"),
                    ("GROOMING", "Grooming"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
